- name: wheat
  chart_id: 2534
  conversion: 27.2155
- name: maize
  chart_id: 2532
  conversion: 25.4
- name: soybean
  chart_id: 2531
  conversion: 27.2155
- name: oats
  chart_id: 2536
  conversion: 14.515
- name: coffee
  chart_id: 2535
  conversion: 0.453592
- name: cotton
  chart_id: 2533
  conversion: 0.453592
- name: sugar
  chart_id: 2537
  conversion: 0.453592
- name: soybean_oil
  chart_id: 2538
  conversion: 0.453592
- name: heating_oil
  chart_id: 2479
  conversion: 3.785
- name: natural_gas
  chart_id: 2478
  conversion: 1
- name: brent_crude_oil
  chart_id: 2480
  conversion: 1
- name: long_term_crude_oil
  chart_id: 1369
  conversion: 1
- name: copper
  chart_id: 1476
  conversion: 0.453592
- name: gold
  chart_id: 1333
  conversion: 28.3495
- name: silver
  chart_id: 1470
  conversion: 28.3495
- name: platinum
  chart_id: 2540
  conversion: 28.3495
- name: palladium
  chart_id: 2542
  conversion: 28.3495
